---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: dumper

commonLabels:
  environment: production
  cluster: shared

commonAnnotations:
  deployed-by: argocd
  cluster: shared
