---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: signoz

commonLabels:
  environment: production
  cluster: shared

commonAnnotations:
  deployed-by: argocd
  cluster: shared

patches:
  - target:
      kind: Ingress
      name: signoz
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: signoz.k8s.local
