---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: arr-stack

resources:
  - ingress.yaml

commonAnnotations:
  deployed-by: argocd
  cluster: shared
