---
# Shared cluster overrides

global:
  annotations:
    deployed-by: argocd
    cluster: shared

nfs:
  server: 10.10.10.13
  volumes:
    - name: media-movies
      pvName: arr-nfs-media-movies
      pvcName: nfs-media-movies
      path: /mnt/bulk/media/movies
      capacity: 1Ti
    - name: media-tv
      pvName: arr-nfs-media-tv
      pvcName: nfs-media-tv
      path: /mnt/bulk/media/tv
      capacity: 1Ti
    - name: media-music
      pvName: arr-nfs-media-music
      pvcName: nfs-media-music
      path: /mnt/bulk/media/music
      capacity: 1Ti
    - name: media-books
      pvName: arr-nfs-media-books
      pvcName: nfs-media-books
      path: /mnt/bulk/media/books
      capacity: 1Ti
    - name: scratch
      pvName: arr-nfs-scratch
      pvcName: nfs-scratch
      path: /mnt/scratch/downloads
      capacity: 1Ti

iscsi:
  portal: 10.10.10.13:3260
  volumes:
    - name: slskd
      pvName: arr-slskd-config
      pvcName: slskd-config
      volumeHandle: pvc-6f9ce57c-20bb-4012-9e44-78ef0e50cfc8
      capacity: 2Gi
    - name: buildarr
      pvName: arr-buildarr-config
      pvcName: buildarr-config
      volumeHandle: pvc-d394dbea-d9f8-45cf-890f-4eeee56ccfc3
      capacity: 1Gi
    - name: prowlarr
      pvName: arr-prowlarr-config
      pvcName: prowlarr-config
      volumeHandle: pvc-02dee8a1-e9c9-42d9-ae5c-789189cdb4b6
      capacity: 2Gi
    - name: sonarr
      pvName: arr-sonarr-config
      pvcName: sonarr-config
      volumeHandle: pvc-400e33b1-0f78-4fe9-92b8-bd8f0dc4a73b
      capacity: 5Gi
    - name: radarr
      pvName: arr-radarr-config
      pvcName: radarr-config
      volumeHandle: pvc-244b84f0-08f3-4c35-a7bd-0ee48bcf2e9f
      capacity: 5Gi
    - name: lidarr
      pvName: arr-lidarr-config
      pvcName: lidarr-config
      volumeHandle: pvc-3b768fb5-66b5-4720-925d-572f30608808
      capacity: 5Gi
    - name: bazarr
      pvName: arr-bazarr-config
      pvcName: bazarr-config
      volumeHandle: pvc-9e5c5fb5-17c9-40f8-829f-398ab823c991
      capacity: 1Gi

csi:
  server: 10.10.10.13
  volumes:
    - name: gluetun
      pvName: gluetun-config
      pvcName: gluetun-config
      volumeHandle: pvc-8b8d1026-1229-41c3-80f2-5bffe3d1b214
      capacity: 1Gi
    - name: qbittorrent
      pvName: arr-qbittorrent-config
      pvcName: qbittorrent-config
      volumeHandle: pvc-a342a73f-ea33-493e-908b-6735cdd09eac
      capacity: 2Gi
    - name: sabnzbd
      pvName: arr-sabnzbd-config
      pvcName: sabnzbd-config
      volumeHandle: pvc-8505ea35-2949-4af7-ba14-514c51a12355
      capacity: 2Gi
    - name: recyclarr
      pvName: arr-recyclarr-config
      pvcName: recyclarr-config
      volumeHandle: pvc-e644590d-829f-4e01-97a4-8a161d9daac2
      capacity: 1Gi
    - name: glance
      pvName: arr-glance-config
      pvcName: glance-config
      volumeHandle: pvc-2f1bfb5f-9a6f-437d-9ff6-342f30c741e4
      capacity: 1Gi

glance:
  jellyfinUserName: sven

ingress:
  enabled: true
  domain: shared.h.svenlito.com
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
  hosts:
    - name: qbittorrent
      service: downloaders
      portName: qbittorrent
    - name: sabnzbd
      service: downloaders
      portName: sabnzbd
    - name: prowlarr
      service: downloaders
      portName: prowlarr
    - name: slskd
      service: downloaders
      portName: slskd
    - name: radarr
      service: radarr
      portName: http
    - name: sonarr
      service: sonarr
      portName: http
    - name: lidarr
      service: lidarr
      portName: http
    - name: bazarr
      service: bazarr
      portName: http
    - name: glance
      service: glance
      portName: http
