---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - sources.yaml
configMapGenerator:
  - name: arr-stack-values
    files:
      - values.yaml=../../apps/arr-stack/overlays/shared/values.yaml
  - name: jellyfin-values
    files:
      - values.yaml=../../apps/jellyfin/overlays/shared/values.yaml
  - name: navidrome-values
    files:
      - values.yaml=../../apps/navidrome/overlays/shared/values.yaml
  - name: postgresql-values
    files:
      - values.yaml=../../apps/postgresql/overlays/shared/values.yaml
  - name: dumper-values
    files:
      - values.yaml=../../apps/dumper/overlays/shared/values.yaml
  - name: osxphotos-export-values
    files:
      - values.yaml=../../apps/osxphotos-export/overlays/shared/values.yaml
  - name: infrastructure-values
    files:
      - values.yaml=../../apps/infrastructure/overlays/shared/values.yaml
  - name: cnpg-operator-values
    files:
      - values.yaml=../../apps/cnpg-operator/overlays/shared/values.yaml
  - name: openobserve-values
    files:
      - values.yaml=../../apps/openobserve/overlays/shared/values.yaml
  - name: vcluster-dev-values
    files:
      - values.yaml=../../apps/vcluster-dev/overlays/shared/values.yaml
  - name: openobserve-collector-agent-values
    files:
      - values.yaml=../../apps/openobserve-collector/overlays/shared/agent-values.yaml
  - name: openobserve-collector-gateway-values
    files:
      - values.yaml=../../apps/openobserve-collector/overlays/shared/gateway-values.yaml
generatorOptions:
  disableNameSuffixHash: true
