---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/svnlto/homelab
  ref:
    branch: main
  secretRef:
    name: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 24h
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: loft
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.loft.sh
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openobserve
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.openobserve.ai
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opentelemetry
  namespace: flux-system
spec:
  interval: 24h
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
