---
apiVersion: v1
kind: Service
metadata:
  name: seerr
  annotations:
    {{- range $key, $val := .Values.global.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  ports:
    - port: {{ .Values.seerr.port }}
      targetPort: {{ .Values.seerr.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "jellyfin.selectorLabels" (dict "name" "seerr") | nindent 4 }}
