---
# Storage network interface
pbs_storage_interface: enp6s19
pbs_storage_ip: 10.10.10.55
pbs_storage_netmask: 24

# NFS datastore
pbs_nfs_server: 10.10.10.13
pbs_nfs_path: /mnt/bulk/backups/proxmox
pbs_nfs_mountpoint: /mnt/pbs-store

# PBS datastore
pbs_datastore_name: nfs-backups

# No-subscription repo
pbs_enterprise_repo: /etc/apt/sources.list.d/pbs-enterprise.list
