---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vcluster-dev
  namespace: vcluster-dev
spec:
  interval: 10m
  releaseName: vcluster-dev
  chart:
    spec:
      chart: vcluster
      version: "0.32.0"
      sourceRef:
        kind: HelmRepository
        name: loft
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: vcluster-dev-values
      valuesKey: values.yaml
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
