---
# Shared cluster overrides

global:
  annotations:
    deployed-by: argocd
    cluster: shared

iscsi:
  portal: 10.10.10.13:3260
  volumes:
    - pvName: dragonfly-data
      pvcName: dragonfly-data
      volumeHandle: pvc-fb5d1277-2699-4a34-b5fb-31bf5c342bfc
      capacity: 2Gi
