---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  labels:
    {{- include "immich.labels" (dict "name" "immich" "context" .) | nindent 4 }}
  annotations:
    {{- include "immich.annotations" . | nindent 4 }}
data:
  DB_HOSTNAME: postgresql-rw.database.svc.cluster.local
  DB_PORT: "5432"
  DB_DATABASE_NAME: immich
  DB_USERNAME: immich
  REDIS_HOSTNAME: dragonfly.cache.svc.cluster.local
  REDIS_PORT: "6379"
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.{{ .Release.Namespace }}.svc:3003
  IMMICH_MEDIA_LOCATION: /usr/src/app/upload
