---
apiVersion: v1
kind: Service
metadata:
  name: immich-server
  labels:
    {{- include "immich.labels" (dict "name" "immich-server" "component" "server" "context" .) | nindent 4 }}
  annotations:
    {{- include "immich.annotations" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "immich.selectorLabels" (dict "name" "immich-server" "context" .) | nindent 4 }}
