---
apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
  labels:
    {{- include "immich.labels" (dict "name" "immich-machine-learning" "component" "machine-learning" "context" .) | nindent 4 }}
  annotations:
    {{- include "immich.annotations" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.machineLearning.port }}
      targetPort: {{ .Values.machineLearning.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "immich.selectorLabels" (dict "name" "immich-machine-learning" "context" .) | nindent 4 }}
