---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use base as foundation
bases:
  - ../../base

# Namespace for shared cluster
namespace: whoami

# Shared cluster labels
commonLabels:
  environment: production
  cluster: shared

# Shared cluster annotations
commonAnnotations:
  deployed-by: argocd
  cluster: shared

# Patches for shared environment
patches:
  - target:
      kind: Deployment
      name: whoami
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Ingress
      name: whoami
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: whoami.shared.h.svenlito.com
      - op: add
        path: /metadata/annotations/traefik.ingress.kubernetes.io~1router.tls.certresolver
        value: letsencrypt
      - op: add
        path: /spec/tls
        value:
          - hosts:
              - whoami.shared.h.svenlito.com
