---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dragonfly
  labels:
    {{- include "dragonfly.labels" . | nindent 4 }}
  annotations:
    {{- include "dragonfly.annotations" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "dragonfly.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dragonfly.selectorLabels" . | nindent 8 }}
      annotations:
        {{- include "dragonfly.annotations" . | nindent 8 }}
    spec:
      containers:
        - name: dragonfly
          image: {{ .Values.dragonfly.image }}
          args:
            - --dir
            - /data
            - --dbfilename
            - dump
            - --cluster_mode=emulated
            - --lock_on_hashtags
            - --default_lua_flags=allow-undeclared-keys
            - --requirepass
            - $(DRAGONFLY_PASSWORD)
          ports:
            - containerPort: {{ .Values.dragonfly.port }}
              name: redis
          env:
            - name: DRAGONFLY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecret.targetSecretName }}
                  key: DRAGONFLY_PASSWORD
          startupProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            tcpSocket:
              port: redis
            periodSeconds: 30
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: redis
            periodSeconds: 10
          resources:
            {{- toYaml .Values.dragonfly.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: dragonfly-data
