---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dragonfly-secrets
  labels:
    {{- include "dragonfly.labels" . | nindent 4 }}
  annotations:
    {{- include "dragonfly.annotations" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: {{ .Values.externalSecret.secretStoreKind }}
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecret.keys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.externalSecret.onePasswordItem }}/{{ . }}
    {{- end }}
