---
apiVersion: v1
kind: Service
metadata:
  name: dragonfly
  labels:
    {{- include "dragonfly.labels" . | nindent 4 }}
  annotations:
    {{- include "dragonfly.annotations" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.dragonfly.port }}
      targetPort: {{ .Values.dragonfly.port }}
      protocol: TCP
      name: redis
  selector:
    {{- include "dragonfly.selectorLabels" . | nindent 4 }}
