---
# Shared cluster overrides

global:
  annotations:
    deployed-by: argocd
    cluster: shared

nfs:
  server: 10.10.10.13
  volumes:
    - name: media-movies
      pvName: jellyfin-nfs-media-movies
      pvcName: nfs-media-movies
      path: /mnt/bulk/media/movies
      capacity: 1Ti
    - name: media-tv
      pvName: jellyfin-nfs-media-tv
      pvcName: nfs-media-tv
      path: /mnt/bulk/media/tv
      capacity: 1Ti
    - name: media-music
      pvName: jellyfin-nfs-media-music
      pvcName: nfs-media-music
      path: /mnt/bulk/media/music
      capacity: 1Ti
    - name: media-books
      pvName: jellyfin-nfs-media-books
      pvcName: nfs-media-books
      path: /mnt/bulk/media/books
      capacity: 1Ti

csi:
  server: 10.10.10.13
  volumes:
    - name: jellyfin-config
      pvName: jellyfin-config
      pvcName: jellyfin-config
      volumeHandle: pvc-c980b589-8804-41e5-80df-de9d5e249bf8
      capacity: 10Gi
    - name: jellyfin-cache
      pvName: jellyfin-cache
      pvcName: jellyfin-cache
      volumeHandle: pvc-8350007f-5c2e-433d-8b52-3b322b9b947f
      capacity: 10Gi
    - name: jellyseerr-config
      pvName: jellyseerr-config
      pvcName: jellyseerr-config
      volumeHandle: pvc-5af7a2ae-39fc-4d3f-8bb5-0de455f16b68
      capacity: 2Gi

jellyfin:
  nodeSelector:
    kubernetes.io/hostname: shared-worker2

ingress:
  enabled: true
  domain: shared.h.svenlito.com
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
  hosts:
    - name: jellyfin
      service: jellyfin
      portName: http
    - name: jellyseerr
      service: jellyseerr
      portName: http
