---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - arr-stack.yaml
  - cnpg-system.yaml
  - database.yaml
  - dumper.yaml
  - infrastructure.yaml
  - jellyfin.yaml
  - navidrome.yaml
  - openobserve.yaml
  - osxphotos-export.yaml
  - vcluster-dev.yaml
