---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openobserve
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://charts.openobserve.ai
      chart: openobserve-standalone
      targetRevision: "0.60.0"
      helm:
        valueFiles:
          - $values/kubernetes/apps/openobserve/overlays/shared/values.yaml
    - repoURL: https://github.com/svnlto/homelab
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/svnlto/homelab
      targetRevision: HEAD
      path: kubernetes/apps/openobserve/overlays/shared
      directory:
        include: "{ingress,external-secret}.yaml"

  destination:
    server: https://kubernetes.default.svc
    namespace: openobserve

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
