---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dumper-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: dumper-config
    creationPolicy: Owner
  data:
    - secretKey: REMOTE_HOST
      remoteRef:
        key: Dumper Config
        property: REMOTE_HOST
    - secretKey: REMOTE_PATH
      remoteRef:
        key: Dumper Config
        property: REMOTE_PATH
    - secretKey: REMOTE_USER
      remoteRef:
        key: Dumper Config
        property: REMOTE_USER
