---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dumper-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: dumper-config
    creationPolicy: Owner
  data:
    - secretKey: REMOTE_HOST
      remoteRef:
        key: dumper-config/REMOTE_HOST
    - secretKey: REMOTE_PATH
      remoteRef:
        key: dumper-config/REMOTE_PATH
    - secretKey: REMOTE_USER
      remoteRef:
        key: dumper-config/REMOTE_USER
