---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - external-secret-tailscale.yaml
  - external-secret-config.yaml
  - external-secret-ssh-key.yaml
  - deployment.yaml
  - pv-nfs.yaml
  - pv-cache.yaml
  - pvc-nfs.yaml
  - pvc-cache.yaml

commonLabels:
  app.kubernetes.io/name: dumper
  app.kubernetes.io/component: rsync
