---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjob.yaml
  - pv-nfs.yaml
  - pvc-nfs.yaml
  - pvc-cache.yaml
  - pvc-tailscale.yaml

commonLabels:
  app.kubernetes.io/name: dumper
  app.kubernetes.io/component: rsync
