---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dumper-cache
  annotations:
    pv.kubernetes.io/provisioned-by: org.democratic-csi.nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: truenas-nfs-bulk
  claimRef:
    namespace: dumper
    name: dumper-cache
  csi:
    driver: org.democratic-csi.nfs
    volumeHandle: pvc-c44edf8b-0bfc-4d0f-a9b4-f36c6129263b
    fsType: nfs
    volumeAttributes:
      server: 10.10.10.13
      share: /mnt/bulk/kubernetes/nfs-dynamic/pvc-c44edf8b-0bfc-4d0f-a9b4-f36c6129263b
      node_attach_driver: nfs
      provisioner_driver: freenas-nfs
  mountOptions:
    - nfsvers=4
    - nconnect=8
    - hard
    - noatime
    - nodiratime
