---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dumper-cache
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs-rwx
  resources:
    requests:
      storage: 100Mi
