---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dumper-cache
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs-bulk
  volumeName: dumper-cache
  resources:
    requests:
      storage: 1Gi
