---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dumper-cache
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: dumper-cache
  resources:
    requests:
      storage: 1Gi
