---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-state
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs-rwx
  resources:
    requests:
      storage: 50Mi
