---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.config.targetSecretName }}
  annotations:
    {{- include "dumper.annotations" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}
  target:
    name: {{ .Values.externalSecrets.config.targetSecretName }}
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.config.keys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.externalSecrets.config.onePasswordItem }}/{{ . }}
    {{- end }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.sshKey.targetSecretName }}
  annotations:
    {{- include "dumper.annotations" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}
  target:
    name: {{ .Values.externalSecrets.sshKey.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.externalSecrets.sshKey.secretKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.sshKey.onePasswordItem }}/{{ .Values.externalSecrets.sshKey.remoteRefKey }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.tailscale.targetSecretName }}
  annotations:
    {{- include "dumper.annotations" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}
  target:
    name: {{ .Values.externalSecrets.tailscale.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.externalSecrets.tailscale.secretKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.tailscale.onePasswordItem }}/{{ .Values.externalSecrets.tailscale.remoteRefKey }}
