---
global:
  annotations:
    deployed-by: argocd
    cluster: shared

staticVolume:
  enabled: true
  pvName: postgresql-data
  volumeHandle: pvc-d543dc0c-3ae4-425e-8f50-433e573a479a
  portal: 10.10.10.13:3260

cluster:
  storage:
    size: 10Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

databases:
  - name: immich
    owner: immich
    extensions:
      - name: vchord
      - name: vector
      - name: earthdistance
