---
- name: Create backup script for {{ job.description }}
  ansible.builtin.template:
    src: restic-backup.sh.j2
    dest: "{{ restic_scripts_dir }}/restic-backup-{{ job.name }}.sh"
    mode: "0700"
  loop: "{{ restic_backup_jobs }}"
  loop_control:
    loop_var: job
    label: "{{ job.name }}"
