---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openobserve-auth
  namespace: openobserve
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: openobserve-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ZO_ROOT_USER_EMAIL: "{{ .username }}"
        ZO_ROOT_USER_PASSWORD: "{{ .password }}"
        OPENOBSERVE_AUTH_HEADER: 'Basic {{ printf "%s:%s" .username .password | b64enc }}'
  data:
    - secretKey: username
      remoteRef:
        key: openobserve/username
    - secretKey: password
      remoteRef:
        key: openobserve/password
