---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osxphotos-export
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: osxphotos-export
  template:
    spec:
      containers:
        - name: osxphotos-export
          image: ghcr.io/svnlto/osxphotos-export:latest
          env:
            - name: EXPORT_DB_PATH
              value: /cache/osxphotos_export.db
            - name: SYNC_INTERVAL
              value: "3600"
            - name: RETRY_INTERVAL
              value: "300"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://signoz-otel-collector.signoz.svc:4318
            - name: OTEL_SERVICE_NAME
              value: osxphotos-export
          envFrom:
            - secretRef:
                name: osxphotos-config
          securityContext:
            runAsUser: 1003
            runAsGroup: 1000
          volumeMounts:
            - name: nfs-source
              mountPath: /mnt/source
              readOnly: true
            - name: nfs-export
              mountPath: /mnt/export
            - name: cache
              mountPath: /cache

      volumes:
        - name: nfs-source
          persistentVolumeClaim:
            claimName: osxphotos-source
        - name: nfs-export
          persistentVolumeClaim:
            claimName: osxphotos-export
        - name: cache
          persistentVolumeClaim:
            claimName: osxphotos-cache
