---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: osxphotos-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: osxphotos-config
    creationPolicy: Owner
  data:
    - secretKey: EXPORT_DEST
      remoteRef:
        key: OSXPhotos Config
        property: EXPORT_DEST
    - secretKey: LIBRARY_PATH
      remoteRef:
        key: OSXPhotos Config
        property: LIBRARY_PATH
