---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - external-secret.yaml
  - deployment.yaml
  - pv-source.yaml
  - pvc-source.yaml
  - pv-export.yaml
  - pvc-export.yaml
  - pv-cache.yaml
  - pvc-cache.yaml

commonLabels:
  app.kubernetes.io/name: osxphotos-export
  app.kubernetes.io/component: photo-export
