---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: signoz
  labels:
    app: signoz
spec:
  rules:
    - host: signoz.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: signoz-frontend
                port:
                  number: 3301
