---
- name: Restart chrony
  ansible.builtin.systemd:
    name: chrony
    state: restarted

- name: Restart sshd
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: Update GRUB
  ansible.builtin.command: update-grub
  changed_when: false

- name: Refresh proxmox-boot-tool
  ansible.builtin.command: proxmox-boot-tool refresh
  changed_when: false

- name: Update initramfs
  ansible.builtin.command: update-initramfs -u -k all
  changed_when: false

- name: Restart dell-fan-control
  ansible.builtin.systemd:
    name: dell-fan-control
    state: restarted
    daemon_reload: true
