---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - pv-music.yaml
  - pvc-music.yaml
  - pv-data.yaml
  - pvc-data.yaml

commonLabels:
  app.kubernetes.io/name: navidrome
  app.kubernetes.io/component: server
