---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: navidrome-data
  resources:
    requests:
      storage: 1Gi
