---
apiVersion: v1
kind: Service
metadata:
  name: navidrome
spec:
  ports:
    - port: 4533
      targetPort: 4533
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: navidrome
