---
# Shared cluster overrides

global:
  annotations:
    deployed-by: argocd
    cluster: shared

nfs:
  server: 10.10.10.13
  volumes:
    - name: music
      pvName: navidrome-nfs-music
      pvcName: nfs-music
      path: /mnt/bulk/media/music
      capacity: 1Ti
      accessMode: ReadOnlyMany

iscsi:
  portal: 10.10.10.13:3260
  volumes:
    - name: data
      pvName: navidrome-data
      pvcName: navidrome-data
      volumeHandle: pvc-f99ca6e8-14d0-4a62-a21d-ffdf6b7bb3e7
      capacity: 1Gi

csi:
  server: 10.10.10.13
  volumes: []

ingress:
  enabled: true
  domain: shared.h.svenlito.com
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
