---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dumper
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: dumper=ghcr.io/svnlto/dumper:~0
    argocd-image-updater.argoproj.io/dumper.update-strategy: semver
    argocd-image-updater.argoproj.io/dumper.allow-tags: regexp:^v[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/dumper.helm.image-name: dumper.image.repository
    argocd-image-updater.argoproj.io/dumper.helm.image-tag: dumper.image.tag
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://github.com/svnlto/homelab
      targetRevision: HEAD
      path: charts/dumper
      helm:
        releaseName: dumper
        valueFiles:
          - $values/kubernetes/apps/dumper/overlays/shared/values.yaml
    - repoURL: https://github.com/svnlto/homelab
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: dumper

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
