---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: navidrome
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://github.com/svnlto/homelab
      targetRevision: HEAD
      path: charts/navidrome
      helm:
        releaseName: navidrome
        valueFiles:
          - $values/kubernetes/apps/navidrome/overlays/shared/values.yaml
    - repoURL: https://github.com/svnlto/homelab
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: navidrome

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  ignoreDifferences: []
