---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://charts.signoz.io
      chart: signoz
      targetRevision: "0.111.0"
      helm:
        valueFiles:
          - $values/kubernetes/apps/signoz/values.yaml
    - repoURL: https://github.com/svnlto/homelab
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: signoz

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

  ignoreDifferences:
    - group: clickhouse.altinity.com
      kind: ClickHouseInstallation
      jsonPointers:
        - /status
