---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/svnlto/homelab
    targetRevision: HEAD
    path: kubernetes/apps/signoz/overlays/shared

  destination:
    server: https://kubernetes.default.svc
    namespace: signoz

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  ignoreDifferences: []
