---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://charts.signoz.io
      chart: signoz
      targetRevision: "0.112.0"
      helm:
        valueFiles:
          - $values/kubernetes/apps/signoz/values.yaml
    - repoURL: https://github.com/svnlto/homelab
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/svnlto/homelab
      targetRevision: HEAD
      path: kubernetes/apps/signoz
      directory:
        include: "ingress.yaml"

  destination:
    server: https://kubernetes.default.svc
    namespace: signoz

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true

  ignoreDifferences: []
