---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildarr
  labels:
    app.kubernetes.io/name: buildarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: buildarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: buildarr
    spec:
      containers:
        - name: buildarr
          image: callum027/buildarr:0.7.8
          command:
            - /bin/sh
            - /config/entrypoint.sh
            - daemon
          env:
            - name: TZ
              value: Europe/Berlin
            - name: RADARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: arr-secrets
                  key: RADARR_API_KEY
            - name: SONARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: arr-secrets
                  key: SONARR_API_KEY
            - name: PROWLARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: arr-secrets
                  key: PROWLARR_API_KEY
            - name: LIDARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: arr-secrets
                  key: LIDARR_API_KEY
            - name: BAZARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: arr-secrets
                  key: BAZARR_API_KEY
          volumeMounts:
            - name: config
              mountPath: /config
            - name: buildarr-tmpl
              mountPath: /config/buildarr.yml.tmpl
              subPath: buildarr.yml.tmpl
              readOnly: true
            - name: entrypoint
              mountPath: /config/entrypoint.sh
              subPath: entrypoint.sh
              readOnly: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: buildarr-config
        - name: buildarr-tmpl
          configMap:
            name: buildarr-config
            items:
              - key: buildarr.yml.tmpl
                path: buildarr.yml.tmpl
        - name: entrypoint
          configMap:
            name: buildarr-config
            defaultMode: 0755
            items:
              - key: entrypoint.sh
                path: entrypoint.sh
