---
apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config-default
data:
  glance.yml: |
    pages:
      - name: Arr Stack
        columns:
          - size: full
            widgets:
              - type: monitor
                cache: 1m
                title: Services
                sites:
                  - title: Radarr
                    url: http://radarr.shared.h.svenlito.com:7878
                    icon: si:radarr
                  - title: Sonarr
                    url: http://sonarr.shared.h.svenlito.com:8989
                    icon: si:sonarr
                  - title: Lidarr
                    url: http://lidarr..shared.h.svenlito.com:8686
                    icon: si:lidarr
                  - title: Bazarr
                    url: http://bazarr.shared.h.svenlito.com:6767
                    icon: si:bazarr
                  - title: Prowlarr
                    url: http://prowlarr.shared.h.svenlito.com:9696
                    icon: si:prowlarr
                  - title: qBittorrent
                    url: http://qbittorrent.shared.h.svenlito.com:8701
                    icon: si:qbittorrent
                  - title: SABnzbd
                    url: http://sabnzbd.shared.h.svenlito.com:8080
                    icon: si:sabnzbd
                  - title: Slskd
                    url: http://slskd.shared.h.svenlito.com:5030
