---
apiVersion: v1
kind: Service
metadata:
  name: downloaders
spec:
  ports:
    - port: 8701
      targetPort: 8701
      protocol: TCP
      name: qbittorrent
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: sabnzbd
    - port: 9696
      targetPort: 9696
      protocol: TCP
      name: prowlarr
    - port: 8191
      targetPort: 8191
      protocol: TCP
      name: flaresolverr
    - port: 5030
      targetPort: 5030
      protocol: TCP
      name: slskd
  selector:
    app.kubernetes.io/name: downloaders
