---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arr-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: arr-secrets
    creationPolicy: Owner
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: Arr Stack Secrets
        property: WIREGUARD_PRIVATE_KEY
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: Arr Stack Secrets
        property: WIREGUARD_ADDRESSES
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: Arr Stack Secrets
        property: RADARR_API_KEY
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: Arr Stack Secrets
        property: SONARR_API_KEY
    - secretKey: PROWLARR_API_KEY
      remoteRef:
        key: Arr Stack Secrets
        property: PROWLARR_API_KEY
    - secretKey: LIDARR_API_KEY
      remoteRef:
        key: Arr Stack Secrets
        property: LIDARR_API_KEY
    - secretKey: BAZARR_API_KEY
      remoteRef:
        key: Arr Stack Secrets
        property: BAZARR_API_KEY
