---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arr-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: arr-secrets
    creationPolicy: Owner
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: Arr Stack Secrets/WIREGUARD_PRIVATE_KEY
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: Arr Stack Secrets/WIREGUARD_ADDRESSES
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: Arr Stack Secrets/RADARR_API_KEY
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: Arr Stack Secrets/SONARR_API_KEY
    - secretKey: PROWLARR_API_KEY
      remoteRef:
        key: Arr Stack Secrets/PROWLARR_API_KEY
    - secretKey: LIDARR_API_KEY
      remoteRef:
        key: Arr Stack Secrets/LIDARR_API_KEY
    - secretKey: BAZARR_API_KEY
      remoteRef:
        key: Arr Stack Secrets/BAZARR_API_KEY
