---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: arr-slskd-config
  resources:
    requests:
      storage: 2Gi
