---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildarr-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs-fast
  resources:
    requests:
      storage: 1Gi
