---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildarr-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: arr-buildarr-config
  resources:
    requests:
      storage: 1Gi
