---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recyclarr-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs-fast
  resources:
    requests:
      storage: 2Gi
