---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildarr-config
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs-fast
  volumeName: arr-buildarr-config
  resources:
    requests:
      storage: 1Gi
