---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resourceset-local-apps.yaml
  - resourceset-external-apps.yaml
  - helmrelease-openobserve.yaml
  - kustomization-openobserve-extras.yaml
  - imagerepository-dumper.yaml
  - imagerepository-osxphotos-export.yaml
  - imagepolicy-dumper.yaml
  - imagepolicy-osxphotos-export.yaml
  - imageupdateautomation-homelab.yaml
