---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - arr-stack
  - jellyfin
  - navidrome
  - postgresql
  - infrastructure
  - dumper
  - osxphotos-export
  - cnpg-operator
  - vcluster-dev
  - openobserve
  - openobserve-collector-agent
  - openobserve-collector-gateway
  - image-automation
