---
apiVersion: v1
kind: Service
metadata:
  name: truenas-primary
  namespace: infrastructure
spec:
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
---
apiVersion: v1
kind: Endpoints
metadata:
  name: truenas-primary
  namespace: infrastructure
subsets:
  - addresses:
      - ip: 10.10.10.13
    ports:
      - port: 443
        name: https
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: truenas-primary
  namespace: infrastructure
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    traefik.ingress.kubernetes.io/service.serversscheme: https
spec:
  tls:
    - hosts:
        - truenas.shared.h.svenlito.com
  rules:
    - host: truenas.shared.h.svenlito.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: truenas-primary
                port:
                  name: https
