---
apiVersion: v1
kind: Service
metadata:
  name: signoz-otel-collector-talos
  namespace: signoz
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.0.1.102"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: otel-collector
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/name: signoz
  ports:
    - name: tcplog-talos
      port: 5140
      targetPort: 5140
      protocol: TCP
